---

vbox_manage_path: /Applications/VirtualBox.app/Contents/MacOS/

vbox_manage_rules:
  ssh-forward:
    protocol: tcp
    host_port: 2222
    guest_port: 22
  webserver-forward:
    protocol: tcp
    host_port: 8500
    guest_port: 80
