SET TERMOUT OFF
COLUMN pdb_name NEW_VALUE pdb
COLUMN hostname NEW_VALUE host

SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS pdb_name FROM DUAL; 
SELECT SYS_CONTEXT('USERENV', 'HOST') AS hostname FROM DUAL;

SPOOL FILE_&pdb._&host..spl

SET TERMOUT ON
-- Dein SQL-Code hier
SPOOL OFF
