#!/bin/bash

OUTPUT="_info.md"

ignore_files=(
  "*.md"
  "_info.md"
  "$(basename "$0")"
)

write_header()
{
  local count

  count="$1"

  {
    echo "# Commands"
    echo ""
    echo "![Scripts](https://img.shields.io/badge/scripts-${count}-blue)"
    echo "![Status](https://img.shields.io/badge/status-maintained-brightgreen)"
    echo ""
    echo "Small utilities, examples and helper scripts for everyday development tasks."
    echo ""
    echo "---"
    echo ""
    echo "## Available Commands"
    echo ""
  } > "$OUTPUT"
}

build_find_args()
{
  local pattern
  local args

  args=()

  for pattern in "${ignore_files[@]}"
  do
    args+=( ! -name "$pattern" )
  done

  echo "${args[@]}"
}

find_files()
{
  local args

  args=$(build_find_args)

  find ./ -type f $args | sort
}

extract_desc()
{
  local file
  local desc

  file="$1"

  desc="$(sed -nE 's/^[[:space:]]*(#|--|\/\/)[[:space:]]*Desc:[[:space:]]*//p' "$file" | head -n1)"

  if [ -z "$desc" ]
  then
    desc="No description"
  fi

  echo "$desc"
}

generate_list()
{
  local file
  local path
  local desc

  while read -r file
  do
    path="${file#./}"
    desc="$(extract_desc "$file")"

    echo "- [$path]($path) → $desc" >> "$OUTPUT"

  done
}

main()
{
  local files
  local count

  files="$(find_files)"
  count="$(echo "$files" | wc -l | tr -d ' ')"

  write_header "$count"

  echo "$files" | generate_list

  {
    echo ""
    echo "---"
    echo ""
    echo "## Notes"
    echo ""
    echo "Each script should contain a description line:"
    echo ""
    echo '```'
    echo "# Desc: Example description"
    echo '```'
    echo ""
    echo "_info.md is automatically generated by [generate_info_markdown.sh](/generate_info_markdown.sh)."
  } >> "$OUTPUT"
}

main