---

- name: "Erstelle Oracle-Verzeichnisse unter {{ oracle_base }}"
  ansible.builtin.file:
    path: "{{ oracle_base }}/{{ item }}"
    state: directory
    owner: oracle
    group: oinstall
    mode: '0755'
  loop:
    - scripts
    - rman
    - scripts/logs

- name: "Create folder for showing error during execution of file template"
  ansible.builtin.file:
    path: "{{ oracle_base }}/{{ item }}"
    state: directory
    owner: oracle
    group: oinstall
    mode: '0000'
  loop:
    - fehler
    - fehler/fehler
