/*
    Mini-AWR für SQL Server
    Fokus: Auslastung, Waits, Concurrency, Blocking, Top Queries

    Ausführen in SSMS.
    Benötigt i.d.R. VIEW SERVER STATE.
    Generated by OpenAI
*/

SET NOCOUNT ON;

DECLARE @sample_seconds int = 60; -- Snapshot-Dauer wie bei AWR Intervall
DECLARE @start_time datetime2 = SYSDATETIME();

PRINT '============================================================';
PRINT ' MINI AWR SNAPSHOT - SQL SERVER';
PRINT ' Start: ' + CONVERT(varchar(30), @start_time, 121);
PRINT ' Sample seconds: ' + CAST(@sample_seconds AS varchar(10));
PRINT '============================================================';


/* ============================================================
   1. Instance / Version / Uptime
   ============================================================ */
PRINT '';
PRINT '--- INSTANCE INFO ---';

SELECT
    @@SERVERNAME AS server_name,
    SERVERPROPERTY('MachineName') AS machine_name,
    SERVERPROPERTY('InstanceName') AS instance_name,
    DB_NAME() as Database_Name,
    SERVERPROPERTY('Edition') AS edition,
    SERVERPROPERTY('ProductVersion') AS product_version,
    SERVERPROPERTY('ProductLevel') AS product_level,
    SERVERPROPERTY('ProductUpdateLevel') AS product_update_level,
    SERVERPROPERTY('ProductUpdateReference') AS kb_reference,
    sqlserver_start_time
FROM sys.dm_os_sys_info;


/* ============================================================
   2. Current CPU Scheduler Pressure
   ============================================================ */
PRINT '';
PRINT '--- SCHEDULER / CPU PRESSURE ---';

SELECT
    scheduler_id,
    current_tasks_count,
    runnable_tasks_count,
    pending_disk_io_count,
    load_factor
FROM sys.dm_os_schedulers
WHERE status = 'VISIBLE ONLINE'
ORDER BY runnable_tasks_count DESC, pending_disk_io_count DESC;


/* ============================================================
   3. Wait Stats Snapshot Start
   ============================================================ */

IF OBJECT_ID('tempdb..#waits_start') IS NOT NULL DROP TABLE #waits_start;
IF OBJECT_ID('tempdb..#waits_end') IS NOT NULL DROP TABLE #waits_end;

SELECT
    wait_type,
    waiting_tasks_count,
    wait_time_ms,
    signal_wait_time_ms
INTO #waits_start
FROM sys.dm_os_wait_stats;


/* ============================================================
   4. Active Requests jetzt
   ============================================================ */
PRINT '';
PRINT '--- CURRENT ACTIVE REQUESTS ---';

SELECT
    r.session_id,
    s.login_name,
    s.host_name,
    s.program_name,
    DB_NAME(r.database_id) AS database_name,
    r.status,
    r.command,
    r.cpu_time,
    r.total_elapsed_time,
    r.reads,
    r.writes,
    r.logical_reads,
    r.wait_type,
    r.wait_time,
    r.last_wait_type,
    r.blocking_session_id,
    r.open_transaction_count,
    SUBSTRING(
        txt.text,
        (r.statement_start_offset / 2) + 1,
        CASE
            WHEN r.statement_end_offset = -1
                THEN LEN(CONVERT(nvarchar(max), txt.text))
            ELSE (r.statement_end_offset - r.statement_start_offset) / 2 + 1
        END
    ) AS running_statement,
    txt.text AS full_batch_text
FROM sys.dm_exec_requests r
JOIN sys.dm_exec_sessions s
    ON r.session_id = s.session_id
OUTER APPLY sys.dm_exec_sql_text(r.sql_handle) txt
WHERE r.session_id <> @@SPID
ORDER BY r.total_elapsed_time DESC;


/* ============================================================
   5. Blocking / Concurrency
   ============================================================ */
PRINT '';
PRINT '--- BLOCKING CHAINS ---';

;WITH blocking AS
(
    SELECT
        r.session_id,
        r.blocking_session_id,
        r.wait_type,
        r.wait_time,
        r.wait_resource,
        DB_NAME(r.database_id) AS database_name,
        r.command,
        r.status,
        r.total_elapsed_time,
        txt.text AS sql_text
    FROM sys.dm_exec_requests r
    OUTER APPLY sys.dm_exec_sql_text(r.sql_handle) txt
    WHERE r.blocking_session_id <> 0
)
SELECT *
FROM blocking
ORDER BY wait_time DESC;


/* ============================================================
   6. Locks aktuell
   ============================================================ */
PRINT '';
PRINT '--- CURRENT LOCKS BY DATABASE / MODE ---';

SELECT
    DB_NAME(resource_database_id) AS database_name,
    resource_type,
    request_mode,
    request_status,
    COUNT(*) AS lock_count
FROM sys.dm_tran_locks
GROUP BY
    resource_database_id,
    resource_type,
    request_mode,
    request_status
ORDER BY lock_count DESC;


/* ============================================================
   7. Schlafen für Snapshot-Differenz
   ============================================================ */
PRINT '';
PRINT 'Collecting wait delta...';

DECLARE @delay varchar(8) =
    RIGHT('00' + CAST(@sample_seconds / 3600 AS varchar(2)), 2) + ':' +
    RIGHT('00' + CAST((@sample_seconds % 3600) / 60 AS varchar(2)), 2) + ':' +
    RIGHT('00' + CAST(@sample_seconds % 60 AS varchar(2)), 2);

WAITFOR DELAY @delay;


/* ============================================================
   8. Wait Stats Snapshot Ende + Delta
   ============================================================ */

SELECT
    wait_type,
    waiting_tasks_count,
    wait_time_ms,
    signal_wait_time_ms
INTO #waits_end
FROM sys.dm_os_wait_stats;

PRINT '';
PRINT '--- TOP WAIT EVENTS DELTA ---';

SELECT TOP 30
    e.wait_type,
    e.waiting_tasks_count - s.waiting_tasks_count AS waiting_tasks_delta,
    e.wait_time_ms - s.wait_time_ms AS wait_time_ms_delta,
    e.signal_wait_time_ms - s.signal_wait_time_ms AS signal_wait_time_ms_delta,
    (e.wait_time_ms - s.wait_time_ms)
      - (e.signal_wait_time_ms - s.signal_wait_time_ms) AS resource_wait_time_ms_delta,
    CASE
        WHEN e.waiting_tasks_count - s.waiting_tasks_count = 0 THEN NULL
        ELSE
            (e.wait_time_ms - s.wait_time_ms) * 1.0
            / NULLIF(e.waiting_tasks_count - s.waiting_tasks_count, 0)
    END AS avg_wait_ms
FROM #waits_start s
JOIN #waits_end e
    ON s.wait_type = e.wait_type
WHERE
    e.wait_time_ms - s.wait_time_ms > 0
    AND e.wait_type NOT IN
    (
        'SLEEP_TASK',
        'BROKER_TASK_STOP',
        'BROKER_TO_FLUSH',
        'SQLTRACE_BUFFER_FLUSH',
        'CLR_AUTO_EVENT',
        'CLR_MANUAL_EVENT',
        'LAZYWRITER_SLEEP',
        'SLEEP_SYSTEMTASK',
        'SLEEP_BPOOL_FLUSH',
        'XE_TIMER_EVENT',
        'XE_DISPATCHER_WAIT',
        'FT_IFTS_SCHEDULER_IDLE_WAIT',
        'BROKER_EVENTHANDLER',
        'REQUEST_FOR_DEADLOCK_SEARCH',
        'HADR_FILESTREAM_IOMGR_IOCOMPLETION',
        'CHECKPOINT_QUEUE',
        'DIRTY_PAGE_POLL',
        'SP_SERVER_DIAGNOSTICS_SLEEP'
    )
ORDER BY wait_time_ms_delta DESC;


/* ============================================================
   9. Top Queries aus Plan Cache
   ============================================================ */
PRINT '';
PRINT '--- TOP QUERIES BY TOTAL CPU FROM PLAN CACHE ---';

SELECT TOP 25
    DB_NAME(txt.dbid) AS database_name,
    qs.execution_count,
    qs.total_worker_time / 1000 AS total_cpu_ms,
    qs.total_elapsed_time / 1000 AS total_elapsed_ms,
    qs.total_logical_reads,
    qs.total_logical_writes,
    qs.total_physical_reads,
    qs.last_execution_time,
    (qs.total_worker_time / NULLIF(qs.execution_count, 0)) / 1000 AS avg_cpu_ms,
    (qs.total_elapsed_time / NULLIF(qs.execution_count, 0)) / 1000 AS avg_elapsed_ms,
    SUBSTRING(
        txt.text,
        (qs.statement_start_offset / 2) + 1,
        CASE
            WHEN qs.statement_end_offset = -1
                THEN LEN(CONVERT(nvarchar(max), txt.text))
            ELSE (qs.statement_end_offset - qs.statement_start_offset) / 2 + 1
        END
    ) AS statement_text,
    txt.text AS full_batch_text,
    qp.query_plan
FROM sys.dm_exec_query_stats qs
CROSS APPLY sys.dm_exec_sql_text(qs.sql_handle) txt
CROSS APPLY sys.dm_exec_query_plan(qs.plan_handle) qp
ORDER BY qs.total_worker_time DESC;


/* ============================================================
   10. Top Queries by Logical Reads
   ============================================================ */
PRINT '';
PRINT '--- TOP QUERIES BY LOGICAL READS FROM PLAN CACHE ---';

SELECT TOP 25
    DB_NAME(txt.dbid) AS database_name,
    qs.execution_count,
    qs.total_logical_reads,
    qs.total_worker_time / 1000 AS total_cpu_ms,
    qs.total_elapsed_time / 1000 AS total_elapsed_ms,
    qs.last_execution_time,
    qs.total_logical_reads / NULLIF(qs.execution_count, 0) AS avg_logical_reads,
    SUBSTRING(
        txt.text,
        (qs.statement_start_offset / 2) + 1,
        CASE
            WHEN qs.statement_end_offset = -1
                THEN LEN(CONVERT(nvarchar(max), txt.text))
            ELSE (qs.statement_end_offset - qs.statement_start_offset) / 2 + 1
        END
    ) AS statement_text,
    txt.text AS full_batch_text
FROM sys.dm_exec_query_stats qs
CROSS APPLY sys.dm_exec_sql_text(qs.sql_handle) txt
ORDER BY qs.total_logical_reads DESC;


/* ============================================================
   11. Query Store Report für aktuelle DB, falls aktiviert
   ============================================================ */
PRINT '';
PRINT '--- QUERY STORE STATUS CURRENT DATABASE ---';

SELECT
    DB_NAME() AS database_name,
    actual_state_desc,
    desired_state_desc,
    readonly_reason,
    current_storage_size_mb,
    max_storage_size_mb,
    query_capture_mode_desc,
    size_based_cleanup_mode_desc
FROM sys.database_query_store_options;

IF EXISTS
(
    SELECT 1
    FROM sys.database_query_store_options
    WHERE actual_state_desc IN ('READ_WRITE', 'READ_ONLY')
)
BEGIN
    PRINT '';
    PRINT '--- QUERY STORE TOP QUERIES LAST 24 HOURS BY CPU ---';

    SELECT TOP 25
        OBJECT_NAME(q.object_id) AS object_name,
        qt.query_sql_text,
        SUM(rs.count_executions) AS executions,
        SUM(rs.avg_cpu_time * rs.count_executions) / NULLIF(SUM(rs.count_executions), 0) / 1000.0 AS avg_cpu_ms,
        SUM(rs.avg_duration * rs.count_executions) / NULLIF(SUM(rs.count_executions), 0) / 1000.0 AS avg_duration_ms,
        SUM(rs.avg_logical_io_reads * rs.count_executions) / NULLIF(SUM(rs.count_executions), 0) AS avg_logical_reads,
        MIN(rsi.start_time) AS first_interval,
        MAX(rsi.end_time) AS last_interval
    FROM sys.query_store_runtime_stats rs
    JOIN sys.query_store_plan p
        ON rs.plan_id = p.plan_id
    JOIN sys.query_store_query q
        ON p.query_id = q.query_id
    JOIN sys.query_store_query_text qt
        ON q.query_text_id = qt.query_text_id
    JOIN sys.query_store_runtime_stats_interval rsi
        ON rs.runtime_stats_interval_id = rsi.runtime_stats_interval_id
    WHERE rsi.start_time >= DATEADD(HOUR, -24, SYSDATETIME())
    GROUP BY
        q.object_id,
        qt.query_sql_text
    ORDER BY avg_cpu_ms DESC;
END
ELSE
BEGIN
    PRINT 'Query Store ist für diese Datenbank nicht aktiv.';
END;


/* ============================================================
   12. TempDB Auslastung
   ============================================================ */
PRINT '';
PRINT '--- TEMPDB USAGE BY SESSION ---';

SELECT TOP 25
    s.session_id,
    se.login_name,
    se.host_name,
    se.program_name,
    (s.user_objects_alloc_page_count - s.user_objects_dealloc_page_count) * 8 / 1024 AS user_objects_mb,
    (s.internal_objects_alloc_page_count - s.internal_objects_dealloc_page_count) * 8 / 1024 AS internal_objects_mb
FROM sys.dm_db_session_space_usage s
JOIN sys.dm_exec_sessions se
    ON s.session_id = se.session_id
ORDER BY
    internal_objects_mb DESC,
    user_objects_mb DESC;


/* ============================================================
   13. Database IO Stats
   ============================================================ */
PRINT '';
PRINT '--- DATABASE FILE IO STATS ---';

SELECT
    DB_NAME(vfs.database_id) AS database_name,
    mf.type_desc,
    mf.physical_name,
    vfs.num_of_reads,
    vfs.num_of_writes,
    vfs.io_stall_read_ms,
    vfs.io_stall_write_ms,
    CASE
        WHEN vfs.num_of_reads = 0 THEN NULL
        ELSE vfs.io_stall_read_ms * 1.0 / vfs.num_of_reads
    END AS avg_read_latency_ms,
    CASE
        WHEN vfs.num_of_writes = 0 THEN NULL
        ELSE vfs.io_stall_write_ms * 1.0 / vfs.num_of_writes
    END AS avg_write_latency_ms
FROM sys.dm_io_virtual_file_stats(NULL, NULL) vfs
JOIN sys.master_files mf
    ON vfs.database_id = mf.database_id
   AND vfs.file_id = mf.file_id
ORDER BY
    ISNULL(vfs.io_stall_read_ms * 1.0 / NULLIF(vfs.num_of_reads, 0), 0)
  + ISNULL(vfs.io_stall_write_ms * 1.0 / NULLIF(vfs.num_of_writes, 0), 0) DESC;


PRINT '';
PRINT '============================================================';
PRINT ' MINI AWR SNAPSHOT FINISHED';
PRINT ' End: ' + CONVERT(varchar(30), SYSDATETIME(), 121);
PRINT '============================================================';