SELECT SQLS.SQL_ID, SQLS.MODULE,
       ROUND(SQLS.ELAPSED_TIME_DELTA / 1000 / 1000
             ,2) ELAPSED_TIME_DELTA_IN_SECONDS,
       sqls.EXECUTIONS_DELTA
  FROM DBA_HIST_SNAPSHOT SNAP
  JOIN DBA_HIST_SQLSTAT SQLS
    ON SNAP.SNAP_ID = SQLS.SNAP_ID
   AND SNAP.CON_ID = SQLS.CON_ID
 WHERE SNAP.CON_ID = SYS_CONTEXT('USERENV'
                                ,'CON_ID')
   AND SNAP.BEGIN_INTERVAL_TIME BETWEEN
       TO_DATE('26.03.2024 10:00'
              ,'DD.MM.YYYY HH24:MI') AND
       TO_DATE('26.03.2024 12:00'
              ,'DD.MM.YYYY HH24:MI')
 ORDER BY SQLS.ELAPSED_TIME_DELTA DESC;
