---
- name: "Check that VMState is poweroff"
  ansible.builtin.assert:
    that:
      - vbox_info_infos_dict[vm_name].VMState in ['poweroff', 'saved']
    fail_msg: "{{ vm_name }} must be in state poweroff or saved!"

- name: "Check Forward Rules"
  ansible.builtin.set_fact:
    vbox_manage_tcp_rules: >-
      {{
        vbox_info_infos_dict[vm_name]
        | dict2items
        | selectattr('key', 'search', 'Forward')
        | map(attribute='value')
        | list
      }}

- name: "Add network rules"
  ansible.builtin.command: >
    "{{ vbox_manage_path }}"/VBoxManage modifyvm {{ vm_name }}
    --nat-pf1="{{ item.key }},{{ item.value.protocol }},,{{ item.value.host_port }},,{{ item.value.guest_port }}"
  loop: "{{ vbox_manage_rules | dict2items }}"
  loop_control:
    label: "{{ vm_name }}:{{ item.key }}"
  changed_when: true
  when:
    - "item.value.enabled"
    - "(item.value.host_port | string ) not in (vbox_manage_tcp_rules | join('\n'))"
    - "item.key not in (vbox_manage_tcp_rules | join('\n'))"

- name: "Remove network rules"
  ansible.builtin.command: >
    "{{ vbox_manage_path }}"/VBoxManage modifyvm "{{ vm_name }}" --nat-pf1 delete "{{ item.key }}"
  loop: "{{ vbox_manage_rules | dict2items }}"
  loop_control:
    label: "{{ vm_name }}:{{ item.key }}"
  changed_when: true
  when:
    - "not item.value.enabled"
    - "item.key in (vbox_manage_tcp_rules | join('\n'))"
