services:
  database:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracledb
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: manager
    volumes:
      - oracledb-data:/opt/oracle/oradata
    healthcheck:
      # tnsping to PDB should be enough
      test: ["CMD-SHELL", "bash -lc 'tnsping FREEPDB1'"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 60s

  ords:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ords
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_PORT: 1521
      # Oracle Free Defaults:
      DB_SERVICENAME: FREEPDB1
      ORDS_PORT: 8080
      # Apex is currently used via oracle-cdn 
      # APEX_PATH: /u01/apex_242/
    ports:
      - "8080:8080"
    volumes:
      - ords-config:/u01/config_ords
      - ords-logs:/u01/logs_ords

volumes:
  oracledb-data:
  ords-config:
  ords-logs:
