---
- name: "Prüfen ob OS zur RedHat-Familie gehört"
  ansible.builtin.assert:
    that:
      - ansible_os_family == "RedHat"
    fail_msg: "Nur Systeme der RedHat-Familie erlaubt!"
    success_msg: "System gehört zur RedHat-Familie."

- name: "Print out shell"
  ansible.builtin.shell: |
    set -eu
    source ~/db.env >/dev/null 2>&1;
    echo "ORACLE_SID=${ORACLE_SID}"
    echo "ORACLE_HOME=${ORACLE_HOME}"
  register: shell_output

- name: "Printout shell"
  ansible.builtin.debug:
    msg: "{{ shell_output.stdout_lines }}"

- name: "Copy test.sh to {{ oracle_base }}/scripts/"
  ansible.builtin.copy:
    src: "test.sh"
    dest: "{{ oracle_base }}/scripts"
    owner: oracle
    group: oinstall
    mode: "0774"

- name: "Run {{ oracle_base }}/scripts/test.sh"
  block:
    - name: "Execute test.sh"
      ansible.builtin.shell: "{{ oracle_base }}/scripts/test.sh"
      register: test_output 
  rescue:
    - name: "pint output for scripts"
      ansible.builtin.debug:
        msg: "{{ test_output.stdout_lines }}"
    - name: "fail"
      ansible.builtin.fail:




